### ISSUE TITLE
How to enable references coded using `mixed-citation`?

### ISSUE THREAD

**Issue by lpanebr** [asmecher/lensGalley#33]
Today the lens viewer only accepts `element-citation`[1].

How should I go about to enable references coded using `mixed-citation`[2]?

[1] https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/element-citation.html
[2] https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/mixed-citation.html

**Comment by asmecher** [comment]
@lpanebr, the Lens Reader is not something we maintain -- this repository is just for the integration of Lens into OJS. See https://github.com/elifesciences/lens.

**Comment by lpanebr** [comment]
Thank you @asmecher for your quick response! 
which version/release or branch of lens do you bundle in OJS?

**Comment by asmecher** [comment]
It's version 2.0.
