### ISSUE TITLE
Links to images aren't replace

### ISSUE THREAD

**Issue by Vitaliy-1** [asmecher/lensGalley#36]
OJS 3.1.2
Lens Viewer Plugin latest stable release for 3.1.2.

For some reason, the method `_getXMLContents` doesn't replace URL to the image. As I remember this worked some time ago, right? 
This was raised on the forum, e. g.: https://forum.pkp.sfu.ca/t/jats-xml-figure-insert-issues-404-not-found/53218
I've tested with it also without success. The link in JATS XML:
```
<fig id="f1">
  <label>Figure 1:</label>
  <caption>
	<title>Title</title>
  </caption>
  <graphic xlink:href="fig1.jpg"/>
 <attrib>Attrib</attrib>
</fig>
```
`article/body/sec/fig...`
With the image file attached to the article named `fig1.jpg` (original filename).

**Comment by withanage** [comment]
@Vitaliy-1 
I have included   the extended lens version  d for OJS 3.1.2, which supports the dependency files.
May be shall we recommend him that ?

![Screenshot from 2019-05-22 18-42-55](https://user-images.githubusercontent.com/1921992/58192651-8dbcbe00-7cc1-11e9-8801-cc08f3794c22.png)

**Comment by Vitaliy-1** [comment]
Hi @withanage,

Have you tested it with the latest OJS, it works? I wondering why it's broken for original Lens Viewer plugin.

**Comment by withanage** [comment]
Hi @Vitaliy-1 
i tested the plugin against  OJS 3.1.2. and got a minor error. Did not dig into  it deeper.
```
 /index.php/stable3_1_2/article/download/2/8 - Uncaught Error: Call to undefined method Application::get() in /home/withanage/projects/stable-3_1_2-2019-03-06/plugins/generic/lensGalley/LensGalleyPlugin.inc.php:157
```

**Comment by jnugent** [comment]
Pull request for this, here:  https://github.com/asmecher/lensGalley/pull/37

**Comment by asmecher** [comment]
Merged and ported to `stable-3_1_2` for the next lens galley plugin releases -- thanks, @jnugent! (And @withanage / @Vitaliy-1.)
