### ISSUE TITLE
MathML not working

### ISSUE THREAD

**Issue by mayolag** [asmecher/lensGalley#38]
I want this article to show maths, but is not working:
http://revistarelap.com/index.php/relap/article/view/136/233
I downloaded the latest version of lensGalley.

**Comment by asmecher** [comment]
@mayolag, it looks like the MathJAX CDN was deprecated and removed. Try this change, which will use their replacement Cloudflare-based CDN instead: https://github.com/asmecher/lensGalley/pull/39

If you can confirm whether that works, I can merge it for the next release.

**Comment by mayolag** [comment]
It didn't work :(

**Comment by asmecher** [comment]
@mayolag, can you confirm whether that change is applied to the site at the URL above? It doesn't appear to be.

**Comment by mayolag** [comment]
Yes, it is.

**Comment by asmecher** [comment]
@mayolag, I'm afraid it's not -- see http://revistarelap.com/plugins/generic/lensGalley/templates/display.tpl, which still refers to `cdn.mathjax.org`. The change in https://github.com/asmecher/lensGalley/pull/39/files should remove that reference and use `cdnjs.cloudflare.com` instead.

**Comment by mayolag** [comment]
I was uploading it in the incorrect place. I corrected it, but now is not
loading :(

**Comment by asmecher** [comment]
@mayolag, hmm, this might be a Mathjax incompatibility? Try changing the `2.7.5` for `2.7.1` (in `plugins/generic/lensGalley/templates/display.tpl`), so the versions in the old CDN and new CDN are the same.

**Comment by mayolag** [comment]
It loads now, but maths are not showing

**Comment by asmecher** [comment]
@mayolag, stepping back, I think this may be more to do with how you've formulated the XML than with the lensGalley plugin. I checked https://gist.github.com/pkra/db08cf423cc1a5aa8eb7 locally and it seems to work (with the above changes in place). Yours gets a repeated Javascript error:
```
Unsupported formula element of type alternatives
```
I think this indicates that Lens Reader itself is having trouble digesting your XML.

**Comment by mayolag** [comment]
I wonder why it works with the embedGalley plugin...

**Comment by asmecher** [comment]
I think you'd need to look into Lens Reader for the answer to that -- the lensGalley plugin is just the glue that connects that tool to OJS. We don't maintain Lens Reader ourselves; it's kept here: https://github.com/elifesciences/lens-reader
...but note that it seems to be no longer receiving updates.

**Comment by asmecher** [comment]
(I did end up committing the change to use the newer JS CDN, but I think the old CDN has a work-around that should work for existing users.)
