### ISSUE TITLE
Error images lens article viewer

### ISSUE THREAD

**Issue by diegomejia071** [asmecher/lensGalley#40]
Hi,

I am using OJS version 3.1.2.0, and the lens article viewer. But when I upload the images to it, he saves them to me in the delivery, but they are not displayed in the lens viewfinder. I get a 404 error.

Regards…

**Comment by asmecher** [comment]
@diegomejia071, could you post this on the PKP support forum at http://forum.pkp.sfu.ca? If it turns out to be a bug, we can migrate it here.

**Comment by asmecher** [comment]
(I see now that this has already been posted at https://forum.pkp.sfu.ca/t/ojs3-problems-with-elife-lens-article-viewer-plugin/19889/28. It'll help us to keep organized if you just post a question in one place, thanks!)
