### ISSUE TITLE
Multilanguage articles with translations in `<sub-article>`s

### ISSUE THREAD

**Issue by lpanebr** [asmecher/lensGalley#53]
Scielo and PMC handle this using `<sub-article>`s[1] for each translation on multilingual articles[2,3].

**Any plans to enable this in the lens plugin?**

[1] https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/sub-article.html
[2] https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/dobs.html#dob-multi-lang
[3] https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-sub-article.html?highlight=sub-article

**Comment by asmecher** [comment]
@lpanebr, the Elife Lens reader is no longer being developed by the Elife team, so we're unlikely to continue developing this plugin.

**Comment by lpanebr** [comment]
Hi @asmecher , I've just asked them (https://github.com/elifesciences/lens/issues/227#issuecomment-1175652139) and as I understand it is still maintained, but only applying security patches (at the moment) due to a priorities vs dev time balance.

**Comment by asmecher** [comment]
That's good news. However, the last release was in 2015, which is a pretty big gap!

**Comment by lpanebr** [comment]
hahhaah, that's a good point! Perhaps the security patches happen silently?
I'll keep watching both repos just in case. 😉

Thanks!

**Comment by asmecher** [comment]
Since Lens Reader runs in the browser, and the documents it reads are "trustworthy" (they go through the full OJS workflow before presentation), security risks in Lens Reader are not major. That said, we generally don't pull unreleased dependencies from github -- it's not good practice.
