### ISSUE TITLE
Unable to replace the version files as existing does not show xml files

### ISSUE THREAD

**Issue by asifdev124** [asmecher/lensGalley#54]
I am unable to load xml galley, just spinning the page. I am tried to remove existint elens version and trying to upload new but it giving me error says, folder name does not match

**Comment by asmecher** [comment]
@asifdev124, the eLife Lens product is discontinued, so we are unlikely to continue developing this plugin. If you need more general assistance, post on our support forum (https://forum.pkp.sfu.ca).
