### ISSUE TITLE
Error in displaying supplementary files - img

### ISSUE THREAD

**Issue by Ppantaleo** [asmecher/lensGalley#68]
Hello, I extend this problem presented in the forum: https://forum.pkp.sfu.ca/t/error-al-visualizar-imagenes-actualizando-desde-version-3-3-0-14-a-3-4-0-4/86655

Problem: In version 3.4.0.4 the XML does not show the image.

In previous versions an image is uploaded as a complementary file and the URL is completed correctly:

![Imagen de WhatsApp 2024-02-26 a las 16 47 32_3b994593](https://github.com/asmecher/lensGalley/assets/74371185/da15efdd-713c-4600-8ae5-64a8d3b85075)

In version 3.4.0.4, the image loads in the same way but is not displayed. Inspecting the URL does not load correctly for the supplementary file.

![2](https://github.com/asmecher/lensGalley/assets/74371185/e9a0c742-3da6-49c9-b51b-c17f6f20f718)

**Comment by Ppantaleo** [comment]
To fix the error with version 3.4.0.4 you had to work with the file LensGalleyPlugin.php

Line 194:

`if ($galley && in_array($galley->getFileType(), ['application/xml', 'text/xml']) && $galley->getData('submissionId') == $fileId)`

Change to:

`if ($galley && in_array($galley->getFileType(), ['application/xml', 'text/xml']) && $galley->getData('submissionFileId') == $fileId)`

A wrong call

line 280:

`$issue = Repo::issue()->getBySubmissionId($galley->getData('submissionId'));`

`$galley->getData('submissionId')` da null

Change to:

//Modificación 27-07-2024 para pasar por encima error
`$submissionFileAux = $galley->getFile();`
`$submissionIdAux = $submissionFileAux->getData('submissionId');`

// Perform variable replacement for journal, issue, site info
`$issue = Repo::issue()->getBySubmissionId($submissionIdAux)`

**Comment by asmecher** [comment]
Thanks, @Ppantaleo! Could you open a pull request with your proposed fix?

**Comment by asmecher** [comment]
Thanks, @netmas and @Ppantaleo!

@withanage, could you review the attached PR?

**Comment by withanage** [comment]
@Ppantaleo  and @netmas 

Sorry, my eralier request did not come properly!
I have reviewed your PR and sent some small comments. Please have a look !

**Comment by asmecher** [comment]
@withanage, I still don't see your comments on https://github.com/asmecher/lensGalley/pull/69 -- did you forget to finalize the review to send the comments?

In any case, I ran into this error [elsewhere (on the forum)](https://forum.pkp.sfu.ca/t/how-to-solve-broken-images-attached-to-or-in-xml-after-updating-from-ojs-version-3-3-19-to-all-versions-in-3-4/93458) and independently fixed it before I found this issue. @Ppantaleo, please try https://github.com/asmecher/lensGalley/commit/f0b477586f35f436ba46376ff917dc6f89955906 and report back if it resolves the problem.

**Comment by asmecher** [comment]
Unfortunately the above fix wasn't quite complete, as pointed out [in this forum post](https://forum.pkp.sfu.ca/t/broken-images-in-xml-after-updating/91107/10). A further tweak was required:

https://github.com/asmecher/lensGalley/commit/1358b1433883b1bb77946c204bcf5a04394ed053

This will be released with OJS 3.4.0-9.

**Comment by Ppantaleo** [comment]
@asmecher Thank you, sorry for the delay.
