### ISSUE TITLE
Update Lens Reader to final 2.0 release (or latest)

### ISSUE THREAD

**Issue by asmecher** [asmecher/lensGalley#9]

**Comment by TobiasWantzen** [comment]
I'd like to draw your kind attention to one paragraph of the eLens 2.0 README.md:
»
A note on mobile
Mobile support has been removed with Lens 2.0 to reduce technical debt and iterate more quickly on features. Eventually the Lens team will come up with a dedicated reader for mobile. We want to solve it right, and eventually also ship native versions for iOS and Android.
«

Upgrading to 2.0 strips the mobile support.

**Comment by asmecher** [comment]
Hmm, good spotting. Perhaps I'll leave things at the current beta until I have a better idea of their timelines.

**Comment by asmecher** [comment]
Updated Lens reader to v2.0. It sounds like eLife doesn't currently have plans to work on an embedded view, and appears to be using a different template that's external to the Lens Reader app when mobile readers are present. Meanwhile, multiple users have had trouble with the older version of Lens Reader not rendering valid XML, so I think this is the lesser evil.

**Comment by jarulin** [comment]
Hi, I have problem with the viewer, It doesn't work, proccess to generate the XML file is waiting while the user is viewing the message "loading article"

**Comment by asmecher** [comment]
@jarulin, I see this is also posted on our support forum (https://forum.pkp.sfu.ca/t/problems-with-elife-lens-article-viewer-plugin/72623) -- that's the best place to get help.
